---
title: "Two-Parameters"
author: "Ryan Bansal"
format: html
execute:
    echo: false
    message: false
    warning: false
---

```{r}
library(tidyverse)
library(primer.data)
library(tidymodels)
library(broom)
library(knitr)
library(marginaleffects)
```

```{r}
set.seed(10)

x <- nhanes |>
  filter(age >= 18 & age <= 27) |>
  select(height, sex) |>
  drop_na() |>
  slice_sample(n = 50) 
```

```{r}
#| cache: true
fit_height <- linear_reg() |>
  fit(height ~ sex, data = x)
```

```{r}

tidy(fit_height, conf.int = TRUE) |>
  select(term, estimate, conf.low, conf.high) |>
  kable(
    caption = "Estimates and 95% Confidence Intervals for Parameters\nSource: NHANES 2009–2011"
  )

```


```{r}
plot_predictions(fit_height, 
                 condition = "sex", 
                 draw = FALSE) |> 
  ggplot(aes(x = sex, y = estimate, color = sex)) +
  geom_pointrange(aes(ymin = conf.low, ymax = conf.high),
                  size = 1.2, 
                  linewidth = 1.5,
                  fatten = 3) +
  scale_color_manual(values = c("Female" = "#E74C3C", "Male" = "#3498DB")) +
  labs(
    title = "Predicted Height by Sex for Marine Recruits",
    subtitle = "Male recruits are estimated to be about 16 cm taller than females",
    caption = "Data source: USMC training set",
    x = NULL,
    y = "Height (cm)",
    color = "Sex"
  ) +
  theme_minimal() +
  theme(legend.position = "none")
```

Men are predicted to be about 16 cm taller than women, on average. The 95% confidence interval for this difference ranges from 12.3 to 19.6 cm, suggesting the result is statistically significant. While this model offers a clear estimate, it may be limited by assumptions and missing variables like age or nutrition.